#!/usr/bin/env bash
# printing 1 to 10, iterating at 4, 5 and 8

i=0

while [ $i -lt 10 ]
do
	if [ $i -eq 4 ]
	then
		echo "bad luck"
	elif [ $i -eq 8 ]
	then
		echo "good luck"
	fi

	echo "Best School"

	(( i++ ))
done
